version: '3.5'

# Declaro los servicios a utilizar
services:
  
  app:
    image: node:alpine
    #volumes:
    #  - data
    working_dir: /usr/src/app/admin-web
    ports:
      - 3000:3000
    command: ls #npm start